"""empty message

Revision ID: 03112e39a280
Revises: d877d2eb8555
Create Date: 2018-02-20 15:29:32.228051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03112e39a280'
down_revision = 'd877d2eb8555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subject_teacher_name', table_name='subject')
    op.drop_constraint('subject_teacher_name_fkey', 'subject', type_='foreignkey')
    op.drop_column('subject', 'teacher_name')
    op.add_column('users', sa.Column('sub_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_sub_id'), 'users', ['sub_id'], unique=False)
    op.create_foreign_key(None, 'users', 'subject', ['sub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_sub_id'), table_name='users')
    op.drop_column('users', 'sub_id')
    op.add_column('subject', sa.Column('teacher_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subject_teacher_name_fkey', 'subject', 'users', ['teacher_name'], ['id'])
    op.create_index('ix_subject_teacher_name', 'subject', ['teacher_name'], unique=False)
    # ### end Alembic commands ###
