"""empty message

Revision ID: 045dd2c51db1
Revises: 43429735606d
Create Date: 2018-01-23 21:01:25.250013

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = '045dd2c51db1'
down_revision = '43429735606d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('date_time', sa.DateTime(), nullable=True))
    op.alter_column('submissions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_submissions_date_time'), 'submissions', ['date_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_date_time'), table_name='submissions')
    op.alter_column('submissions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('submissions', 'date_time')
    # ### end Alembic commands ###
