"""empty message

Revision ID: 20fa0db1b8f1
Revises: 60b4a868f67a
Create Date: 2018-02-20 22:18:41.610591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fa0db1b8f1'
down_revision = '60b4a868f67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachersub_userid_subjectid_key', 'teachersub', type_='unique')
    op.drop_column('teachersub', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachersub', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint('teachersub_userid_subjectid_key', 'teachersub', ['userid', 'subjectid'])
    # ### end Alembic commands ###
