"""empty message

Revision ID: 269dcfbd0883
Revises: 61af4e707f62
Create Date: 2018-02-20 21:44:05.081292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269dcfbd0883'
down_revision = '61af4e707f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachersub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachersub',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subjectid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subjectid'], ['subject.id'], name='teachersub_subjectid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name='teachersub_userid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teachersub_pkey')
    )
    # ### end Alembic commands ###
