"""empty message

Revision ID: 299bd14a7123
Revises: 
Create Date: 2017-12-26 18:19:10.126100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299bd14a7123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('form_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_submissions_form_id'), 'submissions', ['form_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_form_id'), table_name='submissions')
    op.drop_column('submissions', 'form_id')
    # ### end Alembic commands ###
