"""empty message

Revision ID: 385c05be951d
Revises: 7c12e9012054
Create Date: 2018-02-10 07:02:58.764924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385c05be951d'
down_revision = '7c12e9012054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('user_test', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'users', ['user_test'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'user_test')
    # ### end Alembic commands ###
