"""empty message

Revision ID: 3ae16b77a6e7
Revises: 6e3c9e79c1d1
Create Date: 2018-02-20 21:51:52.056916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae16b77a6e7'
down_revision = '6e3c9e79c1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teachersub', ['userid', 'subjectid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachersub', type_='unique')
    # ### end Alembic commands ###
