"""empty message

Revision ID: 43429735606d
Revises: e6cab1012bc5
Create Date: 2018-01-19 17:44:02.100051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43429735606d'
down_revision = 'e6cab1012bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_name', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_name')
    )
    op.add_column('subject', sa.Column('semester', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'semester', ['semester'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'semester')
    op.drop_table('semester')
    # ### end Alembic commands ###
