"""empty message

Revision ID: 45e70727fa0c
Revises: a8b5624522e9
Create Date: 2018-02-10 05:46:11.193992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e70727fa0c'
down_revision = 'a8b5624522e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachersub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachersub',
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subjectid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subjectid'], ['subject.id'], name='teachersub_subjectid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name='teachersub_userid_fkey')
    )
    # ### end Alembic commands ###
