"""empty message

Revision ID: 49b7b047fc06
Revises: 814812b30807
Create Date: 2018-02-10 04:56:11.698895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b7b047fc06'
down_revision = '814812b30807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_teacher_fkey', 'subject', type_='foreignkey')
    op.drop_column('subject', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('teacher', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subject_teacher_fkey', 'subject', 'users', ['teacher'], ['id'])
    # ### end Alembic commands ###
