"""empty message

Revision ID: 60b4a868f67a
Revises: 
Create Date: 2018-02-20 22:14:35.194492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b4a868f67a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electives', sa.Column('stream', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_electives_stream'), 'electives', ['stream'], unique=False)
    op.create_foreign_key(None, 'electives', 'streams', ['stream'], ['id'])
    op.create_unique_constraint(None, 'teachersub', ['userid', 'subjectid'])
    op.drop_constraint('teachersub_subjectid_fkey', 'teachersub', type_='foreignkey')
    op.drop_constraint('teachersub_userid_fkey', 'teachersub', type_='foreignkey')
    op.create_foreign_key(None, 'teachersub', 'subject', ['subjectid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teachersub', 'users', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachersub', type_='foreignkey')
    op.drop_constraint(None, 'teachersub', type_='foreignkey')
    op.create_foreign_key('teachersub_userid_fkey', 'teachersub', 'users', ['userid'], ['id'])
    op.create_foreign_key('teachersub_subjectid_fkey', 'teachersub', 'subject', ['subjectid'], ['id'])
    op.drop_constraint(None, 'teachersub', type_='unique')
    op.drop_constraint(None, 'electives', type_='foreignkey')
    op.drop_index(op.f('ix_electives_stream'), table_name='electives')
    op.drop_column('electives', 'stream')
    # ### end Alembic commands ###
