"""empty message

Revision ID: 61af4e707f62
Revises: c7685094b92b
Create Date: 2018-02-20 15:55:12.802653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61af4e707f62'
down_revision = 'c7685094b92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachersub_userid_fkey', 'teachersub', type_='foreignkey')
    op.drop_constraint('teachersub_subjectid_fkey', 'teachersub', type_='foreignkey')
    op.create_foreign_key(None, 'teachersub', 'subject', ['subjectid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teachersub', 'users', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachersub', type_='foreignkey')
    op.drop_constraint(None, 'teachersub', type_='foreignkey')
    op.create_foreign_key('teachersub_subjectid_fkey', 'teachersub', 'subject', ['subjectid'], ['id'])
    op.create_foreign_key('teachersub_userid_fkey', 'teachersub', 'users', ['userid'], ['id'])
    # ### end Alembic commands ###
