"""empty message

Revision ID: 6e3c9e79c1d1
Revises: 269dcfbd0883
Create Date: 2018-02-20 21:44:59.198379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3c9e79c1d1'
down_revision = '269dcfbd0883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachersub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('subjectid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subjectid'], ['subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachersub')
    # ### end Alembic commands ###
