"""empty message

Revision ID: 6eb5684ee284
Revises: 299bd14a7123
Create Date: 2017-12-27 15:55:11.283889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb5684ee284'
down_revision = '299bd14a7123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('suggestions', sa.Text(), nullable=True))
    op.create_index(op.f('ix_submissions_question_id'), 'submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_submissions_stream_id'), 'submissions', ['stream_id'], unique=False)
    op.create_index(op.f('ix_submissions_subject_id'), 'submissions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_submissions_suggestions'), 'submissions', ['suggestions'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_suggestions'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_subject_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_stream_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_question_id'), table_name='submissions')
    op.drop_column('submissions', 'suggestions')
    # ### end Alembic commands ###
