"""empty message

Revision ID: 7c12e9012054
Revises: 45e70727fa0c
Create Date: 2018-02-10 05:47:04.496738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c12e9012054'
down_revision = '45e70727fa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachersub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('subjectid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subjectid'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachersub')
    # ### end Alembic commands ###
