"""empty message

Revision ID: 814812b30807
Revises: a1ed4caa6e09
Create Date: 2018-02-06 23:56:01.203095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814812b30807'
down_revision = 'a1ed4caa6e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('teacher', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'users', ['teacher'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'teacher')
    # ### end Alembic commands ###
