"""empty message

Revision ID: 9fc250afc02c
Revises: cdfa4a8e842d
Create Date: 2018-02-16 20:54:52.443312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc250afc02c'
down_revision = 'cdfa4a8e842d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elective_name', sa.Unicode(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elective_name')
    )
    op.create_index(op.f('ix_electives_semester_id'), 'electives', ['semester_id'], unique=False)
    op.add_column('subject', sa.Column('elective_name_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subject_elective_name_id'), 'subject', ['elective_name_id'], unique=False)
    op.create_foreign_key(None, 'subject', 'electives', ['elective_name_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_index(op.f('ix_subject_elective_name_id'), table_name='subject')
    op.drop_column('subject', 'elective_name_id')
    op.drop_index(op.f('ix_electives_semester_id'), table_name='electives')
    op.drop_table('electives')
    # ### end Alembic commands ###
