"""empty message

Revision ID: a1ed4caa6e09
Revises: e5b520693de9
Create Date: 2018-02-06 22:57:05.284702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1ed4caa6e09'
down_revision = 'e5b520693de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_date_time', table_name='submissions')
    op.drop_column('submissions', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_submissions_date_time', 'submissions', ['date_time'], unique=False)
    # ### end Alembic commands ###
