"""empty message

Revision ID: a301ec61419f
Revises: 9fc250afc02c
Create Date: 2018-02-19 23:02:56.398069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a301ec61419f'
down_revision = '9fc250afc02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electives', sa.Column('stream', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_electives_stream'), 'electives', ['stream'], unique=False)
    op.create_foreign_key(None, 'electives', 'streams', ['stream'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'electives', type_='foreignkey')
    op.drop_index(op.f('ix_electives_stream'), table_name='electives')
    op.drop_column('electives', 'stream')
    # ### end Alembic commands ###
