"""empty message

Revision ID: a8b5624522e9
Revises: e947b04e900f
Create Date: 2018-02-10 05:39:30.658480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b5624522e9'
down_revision = 'e947b04e900f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachersub', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachersub', 'id')
    # ### end Alembic commands ###
