"""empty message

Revision ID: b3d1d457f9fc
Revises: 385c05be951d
Create Date: 2018-02-10 07:05:41.924661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d1d457f9fc'
down_revision = '385c05be951d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_user_test_fkey', 'subject', type_='foreignkey')
    op.drop_column('subject', 'user_test')
    op.add_column('users', sa.Column('user_test', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subject', ['user_test'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_test')
    op.add_column('subject', sa.Column('user_test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subject_user_test_fkey', 'subject', 'users', ['user_test'], ['id'])
    # ### end Alembic commands ###
