"""empty message

Revision ID: c8d023dcb5b3
Revises: a301ec61419f
Create Date: 2018-02-20 15:21:19.910892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d023dcb5b3'
down_revision = 'a301ec61419f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('teacher_name', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subject_teacher_name'), 'subject', ['teacher_name'], unique=False)
    op.create_foreign_key(None, 'subject', 'users', ['teacher_name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_index(op.f('ix_subject_teacher_name'), table_name='subject')
    op.drop_column('subject', 'teacher_name')
    # ### end Alembic commands ###
