"""empty message

Revision ID: d877d2eb8555
Revises: c8d023dcb5b3
Create Date: 2018-02-20 15:23:18.568595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd877d2eb8555'
down_revision = 'c8d023dcb5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachersub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachersub',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subjectid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subjectid'], ['subject.id'], name='teachersub_subjectid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name='teachersub_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name='teachersub_pkey')
    )
    # ### end Alembic commands ###
