"""empty message

Revision ID: e6cab1012bc5
Revises: 5e491d41fae2
Create Date: 2018-01-10 20:19:55.743724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cab1012bc5'
down_revision = '5e491d41fae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('date', sa.Date()))
    op.create_index(op.f('ix_submissions_date'), 'submissions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_date'), table_name='submissions')
    op.drop_column('submissions', 'date')
    # ### end Alembic commands ###
