"""empty message

Revision ID: e947b04e900f
Revises: 49b7b047fc06
Create Date: 2018-02-10 05:22:48.209024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e947b04e900f'
down_revision = '49b7b047fc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachersub', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachersub', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
