"""empty message

Revision ID: eb2847df33bf
Revises: 045dd2c51db1
Create Date: 2018-02-06 22:25:57.599323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb2847df33bf'
down_revision = '045dd2c51db1'
branch_labels = None
depends_on = None

import datetime

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_datetime'), table_name='submissions')
    op.alter_column('submissions', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('submissions', 'datetime')
    # ### end Alembic commands ###
